import logging
import os
import time

import numpy
import pandas
import pygeoprocessing

# @TODO: ¿move _accumulate_totals logic here? carbon model will no longer need it
from natcap.invest.carbon import _accumulate_totals
from natcap.invest.unit_registry import u

from invest_reports import jinja_env, sdr_ndr_utils, utils
from invest_reports import report_constants

LOGGER = logging.getLogger(__name__)

TEMPLATE = jinja_env.get_template('carbon.html')


def _get_raster_plot_tuples(args_dict):
    input_raster_plot_tuples = [
        ('lulc_bas_path', 'nominal'),
    ]
    if args_dict['calc_sequestration']:
        input_raster_plot_tuples.extend([
            ('lulc_alt_path', 'nominal'),
        ])

    output_raster_plot_tuples = [
        ('c_storage_bas', 'continuous', 'linear'),
    ]
    if args_dict['calc_sequestration']:
        output_raster_plot_tuples.extend([
            ('c_storage_alt', 'continuous', 'linear'),
            ('c_change_bas_alt', 'divergent', 'linear'),
        ])
    if args_dict['do_valuation']:
        output_raster_plot_tuples.extend([
            ('npv_alt', 'continuous', 'linear'),
        ])

    if args_dict['calc_sequestration']:
        intermediate_output_raster_plot_tuples = [[
            (f'c_{pool_type}_bas', 'continuous', 'linear'),
            (f'c_{pool_type}_alt', 'continuous', 'linear')
         ] for pool_type in ['above', 'below', 'dead', 'soil']]
    else:
        intermediate_output_raster_plot_tuples = [[
            (f'c_{pool_type}_bas', 'continuous', 'linear')
            for pool_type in ['above', 'below', 'dead', 'soil']]]

    return (input_raster_plot_tuples,
            output_raster_plot_tuples,
            intermediate_output_raster_plot_tuples)


def _generate_agg_results_table(args_dict, file_registry):
    table_data = [
        (file_registry['c_storage_bas'], 'Baseline Carbon Storage',
            u.metric_ton),
    ]
    if args_dict['calc_sequestration']:
        table_data.extend([
            (file_registry['c_storage_alt'], 'Alternate Carbon Storage',
                u.metric_ton),
            (file_registry['c_change_bas_alt'], 'Change in Carbon Storage',
                u.metric_ton),
        ])
    if args_dict['do_valuation']:
        table_data.extend([
            (file_registry['npv_alt'],
                'Net Present Value of Carbon Change', u.currency),
        ])

    table_df = pandas.DataFrame()

    for (raster_path, description, units) in table_data:
        total = _accumulate_totals(raster_path)
        raster_info = pygeoprocessing.get_raster_info(raster_path)
        pixel_area = abs(numpy.prod(raster_info['pixel_size']))
        # Since each pixel value is in t/ha, ``total`` is in (t/ha * px) = t•px/ha.
        # Adjusted sum = ([total] t•px/ha) * ([pixel_area] m^2 / 1 px) * (1 ha / 10000 m^2) = t.
        summary_stat = total * pixel_area / 10000
        table_df.loc[description, ['Total', 'Units', 'Filename']] = [
            summary_stat, units, os.path.basename(raster_path)]

    return table_df.to_html()


def report(file_registry, args_dict, model_spec, target_html_filepath):
    """Generate an HTML summary of model results.

    Args:
        file_registry (dict): The ``natcap.invest.FileRegistry.registry``
            that was returned by the model's ``execute`` method.
        args_dict (dict): The arguments that were passed to the model's
            ``execute`` method.
        model_spec (natcap.invest.spec.ModelSpec): the model's ``MODEL_SPEC``.
        target_html_filepath (str): path to an HTML file to be generated by
            this function.

    Returns:
        ``None``
    """

    (input_raster_tuples,
     output_raster_tuples,
     intermediate_raster_tuples) = _get_raster_plot_tuples(args_dict)

    input_raster_plot_configs = sdr_ndr_utils.build_raster_plot_configs(
        args_dict, input_raster_tuples)
    inputs_img_src = utils.plot_and_base64_encode_rasters(
        input_raster_plot_configs)
    input_raster_caption = sdr_ndr_utils.generate_caption_from_raster_list(
        [(id, 'input') for (id, _) in input_raster_tuples],
        args_dict, file_registry, model_spec)

    output_raster_plot_configs = sdr_ndr_utils.build_raster_plot_configs(
            file_registry, output_raster_tuples)
    outputs_img_src = utils.plot_and_base64_encode_rasters(
        output_raster_plot_configs)
    output_raster_caption = sdr_ndr_utils.generate_caption_from_raster_list(
        [(id, 'output') for (id, _, _) in output_raster_tuples],
        args_dict, file_registry, model_spec)

    intermediate_raster_plot_configs = [sdr_ndr_utils.build_raster_plot_configs(
            file_registry, tuples) for tuples in intermediate_raster_tuples]
    intermediate_img_srcs = [utils.plot_and_base64_encode_rasters(
        configs) for configs in intermediate_raster_plot_configs]
    intermediate_raster_captions = [sdr_ndr_utils.generate_caption_from_raster_list(
        [(id, 'output') for (id, _, _) in tuples],
        args_dict, file_registry, model_spec) for tuples in intermediate_raster_tuples]

    if args_dict['calc_sequestration']:
        intermediate_headings = [
            'Carbon Maps: Aboveground',
            'Carbon Maps: Belowground',
            'Carbon Maps: Dead',
            'Carbon Maps: Soil',
        ]
    else:
        intermediate_headings = ['Carbon Maps by Pool Type']

    intermediate_rasters = [
        {'heading': heading, 'img_src': img_src, 'caption': caption}
        for (heading, img_src, caption)
        in zip(intermediate_headings,
               intermediate_img_srcs,
               intermediate_raster_captions)
    ]

    input_raster_stats_table = utils.raster_inputs_summary(
        args_dict).to_html(na_rep='')

    output_raster_stats_table = utils.raster_workspace_summary(
        file_registry).to_html(na_rep='')

    agg_results_table = _generate_agg_results_table(args_dict, file_registry)

    with open(target_html_filepath, 'w', encoding='utf-8') as target_file:
        target_file.write(TEMPLATE.render(
            report_script=__file__,
            model_id=model_spec.model_id,
            model_name=model_spec.model_title,
            userguide_page=model_spec.userguide,
            timestamp=time.strftime('%Y-%m-%d %H:%M'),
            args_dict=args_dict,
            agg_results_table=agg_results_table,
            inputs_img_src=inputs_img_src,
            inputs_caption=input_raster_caption,
            outputs_img_src=outputs_img_src,
            outputs_caption=output_raster_caption,
            intermediate_rasters=intermediate_rasters,
            raster_group_caption=report_constants.RASTER_GROUP_CAPTION,
            output_raster_stats_table=output_raster_stats_table,
            input_raster_stats_table=input_raster_stats_table,
            stats_table_note=report_constants.STATS_TABLE_NOTE,
            model_spec_outputs=model_spec.outputs,
        ))

    LOGGER.info(f'Created {target_html_filepath}')
